import type { Metadata } from 'next';
import { MainLayout } from '@/components/layouts/MainLayout';
import { ReactNode } from 'react';
import 'animate.css';
import logo from '@/components/assets/logo.png';

export const metadata: Metadata = {
  title: 'Wucoin.co',
  description: 'Generated by create next app',
  icons: [logo.src],
  keywords: ['wucoin', 'wukoin', 'crypto', 'blockchain', 'web3'],
};

export default function RootLayout(
  props: Readonly<{
    children: ReactNode;
  }>,
) {
  const { children } = props;
  return <MainLayout>{children}</MainLayout>;
}
