import type { Metadata } from 'next';
import './globals.css';
import { MainLayout } from '@/components/layouts/MainLayout';
import { proText } from '@/app/fonts/font';
import { ReactNode } from 'react';
import 'animate.css';
import { FlashToaster } from '@/lib/flash-toaster';
import logo from '@/components/assets/logo.png';
import { AppProvider } from '@/common/Providers/AppProvider';
import Script from 'next/script';

export const metadata: Metadata = {
  title: 'Wucoin.co',
  description: 'Generated by create next app',
  icons: [logo.src],
};

export default function RootLayout(
  props: Readonly<{
    children: ReactNode;
  }>,
) {
  const { children } = props;
  return (
    <html lang="en">
      <Script src="https://telegram.org/js/telegram-widget.js?21" />
      <body className={`${proText.className} antialiased`}>
        <FlashToaster />
        <AppProvider>
          <MainLayout>{children}</MainLayout>
        </AppProvider>
      </body>
    </html>
  );
}
